baseURL: https://suse-projects.github.io
languageCode: en-us
title: SUSE Open Source Projects
disableKinds:
- taxonomy
- term
markup.goldmark.renderer:
  hardWraps: true
params:
  featuredLimit: 9
  featured:
  - Rancher Desktop
  - Harvester
  - Kubewarden
  - Hypper
  - Epinio
  - Opni
  - SLE BCI
  - Trento
  - Aquarium

  categoryMap:
    ai-ml: AI/ML
