baseURL: https://suse-projects.github.io
languageCode: en-us
title: SUSE sources
disableKinds:
- taxonomy
- term
markup.goldmark.renderer:
  hardWraps: true
params:
  featuredLimit: 6
  featured:
  - Rancher Desktop
  - Hypper
  - Epinio
  - Harvester
  - Opni
  - Kubewarden
  - RKE Government
  - Trento
  - Aquarium

  categoryMap:
    ai-ml: AI/ML
